# Nassau Candy Distributor
### Data overview

In [3]:
import pandas as pd
# Load the dataset
data = pd.read_csv('C:/Users/Neeraj_Thakur/OneDrive/Documents/Nassau Candy Distributor/data/nassau_candy_distributor.csv')

In [ ]:
# # run automatic EDA using ydata_profiling

# import ydata_profiling as yp
# profile = yp.ProfileReport(data, title='metadata_report', explorative=True)
# profile.to_file(output_file='C:/Users/Neeraj_Thakur/OneDrive/Documents/Nassau Candy Distributor/metadata_report.html')

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

100%|██████████| 18/18 [00:00<00:00, 21.52it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

In [11]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10194 entries, 0 to 10193
Data columns (total 18 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Row ID          10194 non-null  int64
 1   Order ID        10194 non-null  object
 2   Order Date      10194 non-null  object
 3   Ship Date       10194 non-null  object
 4   Ship Mode       10194 non-null  object
 5   Customer ID     10194 non-null  int64
 6   Country/Region  10194 non-null  object
 7   City            10194 non-null  object
 8   State/Province  10194 non-null  object
 9   Postal Code     10194 non-null  object
 10  Division        10194 non-null  object
 11  Region          10194 non-null  object
 12  Product ID      10194 non-null  object
 13  Product Name    10194 non-null  object
 14  Sales           10194 non-null  float64
 15  Units           10194 non-null  int64
 16  Gross Profit    10194 non-null  float64
 17  Cost            10194 non-null  float64
dtypes: float64(3), int64(3), object(12)
memory usage: 1.4+ MB

In [12]:
# lets have a look on the data
data.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Country/Region,City,State/Province,Postal Code,Division,Region,Product ID,Product Name,Sales,Units,Gross Profit,Cost
0,1,US-2021-103800-CHO-MIL-31000,03-01-2024,30-06-2026,Standard Class,103800,United States,Houston,Texas,77095,Chocolate,Interior,CHO-MIL-31000,Wonka Bar - Milk Chocolate,6.50,2,4.22,2.28
1,2,US-2021-112326-CHO-TRI-54000,04-01-2024,01-07-2026,Standard Class,112326,United States,Naperville,Illinois,60540,Chocolate,Interior,CHO-TRI-54000,Wonka Bar - Triple Dazzle Caramel,7.50,2,4.90,2.60
2,3,US-2021-112326-CHO-NUT-13000,04-01-2024,01-07-2026,Standard Class,112326,United States,Naperville,Illinois,60540,Chocolate,Interior,CHO-NUT-13000,Wonka Bar - Nutty Crunch Surprise,10.47,3,7.47,3.00
3,4,US-2021-112326-CHO-SCR-58000,04-01-2024,01-07-2026,Standard Class,112326,United States,Naperville,Illinois,60540,Chocolate,Interior,CHO-SCR-58000,Wonka Bar -Scrumdiddlyumptious,10.80,3,7.50,3.30
4,5,US-2021-141817-CHO-TRI-54000,05-01-2024,05-07-2026,Standard Class,141817,United States,Philadelphia,Pennsylvania,19143,Chocolate,Atlantic,CHO-TRI-54000,Wonka Bar - Triple Dazzle Caramel,11.25,3,7.35,3.90

In [13]:
# take sample from big dataset
data.sample(10)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Country/Region,City,State/Province,Postal Code,Division,Region,Product ID,Product Name,Sales,Units,Gross Profit,Cost
8386,8387,US-2024-111241-CHO-FUD-51000,20-08-2025,12-02-2030,Second Class,111241,United States,Fresno,California,93727,Chocolate,Pacific,CHO-FUD-51000,Wonka Bar - Fudge Mallows,18.00,5,12.00,6.00
9747,9748,US-2024-143756-CHO-TRI-54000,02-12-2025,28-05-2030,First Class,143756,United States,Salem,Virginia,24153,Chocolate,Gulf,CHO-TRI-54000,Wonka Bar - Triple Dazzle Caramel,7.50,2,4.90,2.60
4200,4201,US-2023-100461-CHO-MIL-31000,08-01-2025,04-07-2028,Standard Class,100461,United States,Franklin,Wisconsin,53132,Chocolate,Interior,CHO-MIL-31000,Wonka Bar - Milk Chocolate,22.75,7,14.77,7.98
4202,4203,US-2023-137295-CHO-FUD-51000,08-01-2025,05-07-2028,Standard Class,137295,United States,Raleigh,North Carolina,27604,Chocolate,Gulf,CHO-FUD-51000,Wonka Bar - Fudge Mallows,7.20,2,4.80,2.40
7882,7883,US-2024-102337-CHO-SCR-58000,13-06-2025,07-12-2029,First Class,102337,United States,Chicago,Illinois,60653,Chocolate,Interior,CHO-SCR-58000,Wonka Bar -Scrumdiddlyumptious,14.40,4,10.00,4.40
287,288,US-2021-128055-CHO-SCR-58000,31-03-2024,26-09-2026,Standard Class,128055,United States,San Francisco,California,94122,Chocolate,Pacific,CHO-SCR-58000,Wonka Bar -Scrumdiddlyumptious,7.20,2,5.00,2.20
3534,3535,US-2022-113145-CHO-MIL-31000,01-11-2024,27-04-2028,Standard Class,113145,United States,New York City,New York,10011,Chocolate,Atlantic,CHO-MIL-31000,Wonka Bar - Milk Chocolate,16.25,5,10.55,5.70
6223,6224,US-2023-124667-CHO-MIL-31000,11-11-2025,08-05-2029,Standard Class,124667,United States,New York City,New York,10011,Chocolate,Atlantic,CHO-MIL-31000,Wonka Bar - Milk Chocolate,3.25,1,2.11,1.14
6487,6488,US-2023-143154-CHO-NUT-13000,02-12-2025,30-05-2029,Standard Class,143154,United States,Longmont,Colorado,80501,Chocolate,Pacific,CHO-NUT-13000,Wonka Bar - Nutty Crunch Surprise,10.47,3,7.47,3.00
7339,7340,US-2024-134495-CHO-SCR-58000,01-04-2025,25-09-2029,Second Class,134495,United States,Jacksonville,Florida,32216,Chocolate,Gulf,CHO-SCR-58000,Wonka Bar -Scrumdiddlyumptious,10.80,3,7.50,3.30

In [14]:
data.describe()

,Row ID,Customer ID,Sales,Units,Gross Profit,Cost
count,10194.000000,10194.000000,10194.000000,10194.000000,10194.000000,10194.000000
mean,5097.500000,134468.961154,13.908537,3.791838,9.166451,4.742087
std,2942.898656,20231.483007,11.341020,2.228317,6.643740,5.061647
min,1.000000,100006.000000,1.250000,1.000000,0.250000,0.600000
25%,2549.250000,117212.000000,7.200000,2.000000,4.900000,2.400000
50%,5097.500000,133550.000000,10.800000,3.000000,7.470000,3.600000
75%,7645.750000,152051.000000,18.000000,5.000000,12.250000,5.700000
max,10194.000000,192314.000000,260.000000,14.000000,130.000000,130.000000

In [15]:
# check the shape of the data
data.shape

(10194, 18)